name: mongo_dart
version: 0.4.1-dev.10.1
description: MongoDB driver for Dart
homepage: https://github.com/mongo-dart/mongo_dart
environment:
  sdk: '>=2.5.2 <3.0.0'
dependencies:
  bson: '^0.3.2'
  crypto: '^2.0.6'
  logging: '^0.11.3+2'
  mongo_dart_query: '^0.4.1'
  collection: '^1.14.11'
  path: '^1.6.2'
  pool: ^1.4.0
  uuid: ^2.0.0
dev_dependencies:
  test: ^1.3.0
  pedantic: ^1.9.0

