name: mongo_dart
version: "0.5.0-dev.3"
description: "MongoDB driver, implemented in pure Dart. All CRUD operations, aggregation pipeline and more!"
homepage: "https://github.com/mongo-dart/mongo_dart"

dependencies:
  basic_utils: 2.7.1
  bson: 0.3.4
  collection: 1.15.0
  crypto: 2.1.5
  logging: 0.11.4
  mongo_dart_query: 0.4.2
  path: 1.8.0
  pool: 1.5.0
  rational: 0.3.8

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.13.0
  uuid: ^2.2.0

environment:
  sdk: ">=2.7.1 <3.0.0"
